name: Superheroes
version: ${version}
main: me.xemor.superheroes.Superheroes
api-version: 1.16
authors: [Xemor_]
softdepend: [SkillsLibrary2]
description: Adds superheroes to your world - these can be customized completely and are extremely modular.
commands:
  hero:
    description: The root command of all of the commands within Superheroes
    usage: /hero <hero> <name>
permissions:
  superheroes.hero:
    description: Allows them to use /hero
    default: op
  superheroes.reroll:
    description: Allows them to use /reroll
    default: op
  superheroes.hero.others:
    description: Allows them to use /hero on other people
    default: op
  superheroes.hero.bypasscooldown:
    description: Allows them to use /hero regardless of whether it is on cooldown or not
    default: op
  superheroes.notify:
    description: Get informed about new updates to the Superheroes plugin!
    default: op
  superheroes.check:
    description: Allows the user to check what their own hero is
    default: true
  superheroes.check.others:
    description: Allows the user to check what other people's hero is
    default: op